//  #include <stdio.h>
 
//  void hailstone(int n) {
//     int cnt = 1;
//     printf("Hailstone generated by %d:\n", n);
//     if (n == 1) {
//         printf("%d\n", n);
//     } else {
//         while (n != 1) {
//             if (cnt != 1 && (cnt-1) % 6 == 0) printf("\n");
//             printf("%4d", n);
//             if (n % 2 == 0) n /= 2;
//             else n = 3 * n + 1;
//             cnt++;
//         }
//         if ((cnt-1) % 6 == 0) printf("\n");
//         printf("%4d\n", n);
//     }
//     printf("Number of hailstone generated: %d", cnt);
//  }
//  int main(void)
//  {
//      int n;
//      scanf("%d", &n);
//      hailstone(n);
//      return 0;
//  }



//  #include <stdio.h>
 
//  int digit(int n, int k) {
//     int n_ = 0;
//     int k_;
//     int judge;
//     do {
//         n_++;
//         if (n_ == k) k_ = n % 10;
//         n /= 10;
//     } while (n != 0);
//     if (k > n_) judge = -1;
//     else judge = k_;
//     return judge;
//  }
//  int main(void)
//  {
//      int n,k;
     
//      scanf("%d%d", &n, &k);
//      printf("%d", digit(n,k));
//      return 0;
//  }



//  #include <stdio.h>

//  int fun (void) {
//     char ch;
//     if ((scanf("%c", &ch)) == EOF) return 0;
//     fun();
//     printf("%c", ch);
//     return 0;
//  }
 
//  int main(void)
//  {
//     while (fun());

//     return 0;
//  }



// #include <stdio.h>
// #include <stdlib.h>
// #include <time.h>
 
// long F(int n, int* nums) {
//    if (nums[n] != 0) {
//       return nums[n];
//    }

//    if(n==1||n==2) {
//       nums[1] = nums[2] = 1;
//       return nums[1];
//    } else {
//       int last1 = nums[n-1] = F(n-1, nums);
//       int last2 = nums[n-2] = F(n-2, nums);
//       return last1 + last2;
//    }
// }

// int main()
// {
//    int n;
//    scanf("%d",&n);
//    int n_ = n;

//    int* nums = (int*) malloc ( sizeof(int) * (n+1));
//    for (int* index = nums; n_ >= 0; --n_) {
//       *index++ = 0;
//    }

//    double t1 = clock();
//    for (int i = 0; i < 1e8; i++) {
//       F(n, nums);
//    }
//    double t2 = clock();
//    printf("%lf", t2-t1);

//    return 0;
// }



#include <stdio.h>
#include <stdlib.h>
long F(int fib_index, int* fib_cache) {
   // 记忆化编程，存储计算结果方便放回
   if (fib_cache[fib_index] != 0) {
       return fib_cache[fib_index];
   }
   // 第1、2项均为1
   if (fib_index == 1 || fib_index == 2) {
       fib_cache[1] = fib_cache[2] = 1;
       return fib_cache[1];
   } else {
      // 递归计算前两项，并存入缓存
      int prev_one = fib_cache[fib_index - 1] = F(fib_index - 1, fib_cache);
      int prev_two = fib_cache[fib_index - 2] = F(fib_index - 2, fib_cache);
      return prev_one + prev_two;
   }
}

int main() {
   int input_index;
   scanf("%d", &input_index);
   int temp_var = input_index;  // 临时变量，用作循环条件
    
   // 动态分配数组，用于缓存
   int* fib_cache = (int*)malloc(sizeof(int) * (input_index + 1));
   // 缓存数组初始化为0
   for (int* cache_ptr = fib_cache; temp_var >= 0; --temp_var) {
        *cache_ptr++ = 0;
   }
    
   printf("%ld", F(input_index, fib_cache));
    
   free(fib_cache);  // 释放动态分配的内存
   return 0;
}



// #include <stdio.h>
// #include <time.h>
 
// long F(int n) {
//     if(n==1||n==2)
//         return 1;
//     else
//         return F(n-1)+F(n-2);
// }

// int main()
// {
//     int n;
//     scanf("%d",&n);
//    //  printf("%ld",F(n));

//    double t1 = clock();
//    for (int i = 0; i < 1e8; i++) {
//       F(n);
//    }
//    double t2 = clock();
//    printf("%lf", (t2-t1) / CLK_TCK);

//     return 0;
// }



// #include <stdio.h>

// int main(void) {
    
//     return 0;
// }